# Generated by Django 3.0 on 2020-08-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(default='books/default-Image.jpg', upload_to='books'),
        ),
    ]
