# Generated by Django 3.0 on 2020-08-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.CharField(default='testing', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='note',
            field=models.CharField(max_length=500),
        ),
    ]
