# Generated by Django 3.0 on 2020-08-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200806_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.ImageField(default='defaultImage', upload_to='books'),
            preserve_default=False,
        ),
    ]
