# Generated by Django 3.0 on 2020-08-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_book_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='books'),
        ),
    ]
